### PR TITLE
Fret numbers

### PR DESCRIPTION
**Pull request by dreynolds**
Display fret numbers to make the diagram a little easier to read

### CODE REVIEW

**Comment by danielkaczmarczyk** [comment]
I would prefer not to use numbers, but markers for frets 3, 5, 7, 9, 12, 15, 17, 19, 21 and 24. Two line printout with *'s as markers would be sufficient and also that would eliminate the spacing problem. What do you think?

**Comment by dreynolds** [comment]
Yeh, that makes sense. Shall we close this PR and I'll make another when I've recoded it?

**Comment by danielkaczmarczyk** [comment]
no, no let's leave it, we know what's it about

**Comment by danielkaczmarczyk** [comment]
lol sorry I'll close it, I thought it's an issue, not a pr

**Pull request closed without merging**
